resourceKey = "chain_mining_1"
canUseAlone = true
ability = "none"

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "items/data_module.png"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "chain_mining_1"

[abilityConfig]
[[abilityConfig.definition]]
key = "chainMiningRadius"
type = "int"
value = 3
